### PR TITLE
Add option for using the isUsingIjData flag - Fixes #42

### LINKED ISSUE #42: Add option for using the isUsingIjData flag
This is similar to #38, but related to the --isUsingIjData flag right now. There's currently no way to it on the compiler through soynode, since there's no option for it. 

Missing flags like this make me think that maybe soynode could instead have an easy way to pass flags, without having to have an option for each of them. That would probably mean a bigger change though, just thought it'd be good to mention.

So for now I have this working with an extra option on a local branch of mine, I'll send a pull request with it soon.

### PR DESCRIPTION
**Pull request by mairatma**

### CODE REVIEW

**Comment by nicks** [comment]
hmmm...I'm really confused. I've been using ijData for years and I've never needed this flag before? is there something I'm missing?

**Comment by nicks** [comment]
looking at the soy compiler code, I think what happens here is that it automatically turns on IJ mode if it sees you using $ij anywhere. 
https://github.com/google/closure-templates/blob/master/java/src/com/google/template/soy/jssrc/internal/JsSrcMain.java#L111

I'm not sure if this behavior actually makes sense for soynode, given that soynode sometimes tries to break up file compilation into parts. Maybe it shouldn't be an option at all--maybe we should just always pass this flag?

**Comment by mairatma** [comment]
Yeah, it's only needed if templates are not all compiled together, since then the compiler does not always know to pass down $ij data to the templates without knowing the whole context in which they'll run, which is the use case I'm getting right now, and that use case is probably why the flag was added to the compiler.

It's fine for me if you prefer to always pass the flag too, as long as there's some way to use it then it'd be great, since it will cover this missing use case.

Let me know if you'd prefer for me to update this pr or to make this change yourself in that case.

**Comment by nicks** [comment]
ok, I'm going to ask on the mailing list to see if there's any good reason not to turn it on by default.

**Comment by mairatma** [comment]
Thanks! Let me know when you get an answer from them.

**Comment by nicks** [comment]
answered! I turned it on by default and published as 0.7.4

**Comment by mairatma** [comment]
Thanks again!

**Pull request merged**
